### ISSUE TITLE
DJI SDK 3.3 does not contain bitcode and when i build using Xcode 8 giving error "Can archive as bitcode is not supported by DJI sdk framework"

### ISSUE THREAD

**Issue by dhruvappstack** [DJI-Mobile-SDK-Tutorials/iOS-Phantom4Missions#1]
I am building iOS app using Swift 3 .DJI SDK 3.3 does not contain bitcode and when i build archive using Xcode 8 .AppStore does not upload any app if any framework does not contains bitcode in build.Please provide solution as soon possible.
How to upload app using DJI SDK 3.3 which does not contains bitcode?

**Comment by oliverou** [comment]
Hi @EonKid, thanks for your feedbacks. The DJI SDK 3.3 support bitcode now. Please get the latest SDK from DJI Developer Website: https://developer.dji.com/mobile-sdk/downloads/ and try again. BTW, could you send us the screenshot of the error when you fail to upload the app using Xcode 8? 

If you also use the VideoPreviewer in your project, please enable bitcode of it too. Thanks!

**Comment by dhruvappstack** [comment]
Unable to archive using Xcode 8 Swift 3 project
I downloaded the sdk from your provided links getting following error:
ld: bitcode bundle could not be generated because '/Users/dhruv.singh/Desktop/25.10.2016/MYApp/DJISDK.framework/DJISDK' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by oliverou** [comment]
Hi @EonKid, after investigating the issue, we suggest you to disable the bitcode setting in your Xcode project and build archive for app uploading to App Store currently.

![screen shot 2016-10-26 at 6 15 43 pm](https://cloud.githubusercontent.com/assets/13310805/19722210/3e8e14b6-9ba8-11e6-865b-6f0a7f280c9e.png)

We will try to fix the bitcode support issue of DJI SDK in the future SDK version release.

**Comment by dhruvappstack** [comment]
But i have uploaded many apps recently .But apps with sdk version without bitcode  cannot be uploaded to AppStore .When i tried to upload the app by disabling bitcode the apple rejected to upload build on AppStore iTunes connect account.

**Comment by oliverou** [comment]
Hi @EonKid, understand your situation. If it's not very urgent for you, could you wait for a few days? We will release a new SDK version very soon. And it should fix this bitcode issue.

**Comment by dhruvappstack** [comment]
Thanks @oliverou  i can wait .

**Comment by dji-dev** [comment]
Hi @EonKid, we have just released the DJI SDK 3.4, and it fully supports **bitcode** now, please get the latest SDK from DJI Developer Website and try if it can resolve your issue. Thanks!

**Comment by dhruvappstack** [comment]
Hi @dji-dev thanks for your update
